/* The following code was generated by JFlex 1.4.3 on 1/17/13 5:45 PM */

package IC.Parser;

/**
 * The lexical analyzer for the IC language.
 * This specification will be the input of JFlex.
 *
 */
 
 

public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;
  public static final int REGULAR_COMMENT = 6;
  public static final int INLINE_COMMENT = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  6, 48,  0,  0,  6,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    50, 14, 47, 49, 49, 31, 18, 49,  7,  8, 29, 27, 32, 28, 34, 30, 
     5,  4,  4,  4,  4,  4,  4,  4,  4,  4, 49, 33, 15, 13, 16, 49, 
    49,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 
     2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  9, 51, 10, 49,  3, 
    49, 24, 38, 36, 41, 22, 23, 42, 43, 35,  1, 45, 25,  1, 37, 39, 
     1,  1, 20, 26, 19, 21, 40, 44, 46,  1,  1, 11, 17, 12, 49,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\1\3\2\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\2\1\6\2\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\6\2\1\30\1\31\1\32\1\33\1\34"+
    "\1\31\1\35\1\5\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\10\2\1\45\1\46\1\47\11\2\1\50"+
    "\1\51\1\52\1\53\1\54\11\2\1\55\3\2\1\56"+
    "\4\2\1\57\1\60\1\2\1\61\7\2\1\62\2\2"+
    "\1\63\3\2\1\64\3\2\1\65\1\2\1\66\1\2"+
    "\1\67\1\70\1\2\1\71\1\72\1\73\2\2\1\74"+
    "\1\2\1\75\1\76";

  private static int [] zzUnpackAction() {
    int [] result = new int[138];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\320\0\u0104\0\u0138\0\u016c"+
    "\0\u01a0\0\320\0\320\0\320\0\320\0\320\0\320\0\320"+
    "\0\u01d4\0\u0208\0\u023c\0\u0270\0\u02a4\0\u02d8\0\u030c\0\u0340"+
    "\0\u0374\0\u03a8\0\u03dc\0\u0410\0\320\0\320\0\320\0\u0444"+
    "\0\320\0\320\0\320\0\320\0\u0478\0\u04ac\0\u04e0\0\u0514"+
    "\0\u0548\0\u057c\0\320\0\320\0\u05b0\0\320\0\320\0\u05e4"+
    "\0\320\0\u0618\0\u064c\0\320\0\320\0\320\0\320\0\320"+
    "\0\320\0\u0680\0\u06b4\0\u06e8\0\u071c\0\u0750\0\u0784\0\u07b8"+
    "\0\u07ec\0\320\0\320\0\u0104\0\u0820\0\u0854\0\u0888\0\u08bc"+
    "\0\u08f0\0\u0924\0\u0958\0\u098c\0\u09c0\0\320\0\320\0\320"+
    "\0\320\0\320\0\u09f4\0\u0a28\0\u0a5c\0\u0a90\0\u0ac4\0\u0af8"+
    "\0\u0b2c\0\u0b60\0\u0b94\0\u0104\0\u0bc8\0\u0bfc\0\u0c30\0\u0104"+
    "\0\u0c64\0\u0c98\0\u0ccc\0\u0d00\0\u0104\0\u0104\0\u0d34\0\u0104"+
    "\0\u0d68\0\u0d9c\0\u0dd0\0\u0e04\0\u0e38\0\u0e6c\0\u0ea0\0\u0104"+
    "\0\u0ed4\0\u0f08\0\u0104\0\u0f3c\0\u0f70\0\u0fa4\0\u0104\0\u0fd8"+
    "\0\u100c\0\u1040\0\u0104\0\u1074\0\u0104\0\u10a8\0\u0104\0\u0104"+
    "\0\u10dc\0\u0104\0\u0104\0\u0104\0\u1110\0\u1144\0\u0104\0\u1178"+
    "\0\u0104\0\u0104";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[138];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\1\5\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\6\1\31\1\32"+
    "\1\6\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\6"+
    "\1\51\3\6\1\52\2\6\1\53\1\12\1\5\1\12"+
    "\1\5\1\54\5\55\1\54\50\55\1\56\1\57\2\55"+
    "\1\60\60\12\1\61\40\12\1\62\26\12\65\0\5\6"+
    "\15\0\10\6\10\0\14\6\6\0\5\7\15\0\10\7"+
    "\10\0\14\7\11\0\2\10\62\0\1\63\1\11\73\0"+
    "\1\64\63\0\1\65\63\0\1\66\63\0\1\67\67\0"+
    "\1\70\64\0\1\71\42\0\5\6\15\0\1\6\1\72"+
    "\6\6\10\0\10\6\1\73\3\6\6\0\5\6\15\0"+
    "\3\6\1\74\4\6\10\0\14\6\6\0\5\6\15\0"+
    "\6\6\1\75\1\6\10\0\13\6\1\76\6\0\5\6"+
    "\15\0\5\6\1\77\2\6\10\0\14\6\6\0\5\6"+
    "\15\0\3\6\1\100\4\6\10\0\14\6\6\0\5\6"+
    "\15\0\1\101\7\6\10\0\14\6\42\0\1\102\1\103"+
    "\26\0\5\6\15\0\4\6\1\104\3\6\10\0\2\6"+
    "\1\105\11\6\6\0\5\6\15\0\6\6\1\106\1\6"+
    "\10\0\4\6\1\107\7\6\6\0\5\6\15\0\2\6"+
    "\1\110\1\111\4\6\10\0\14\6\6\0\5\6\15\0"+
    "\1\6\1\112\6\6\10\0\4\6\1\113\7\6\6\0"+
    "\5\6\15\0\10\6\10\0\4\6\1\114\7\6\6\0"+
    "\5\6\15\0\10\6\10\0\10\6\1\115\3\6\6\0"+
    "\5\55\1\0\50\55\2\0\2\55\1\0\23\116\1\117"+
    "\21\116\1\120\11\116\1\121\2\116\1\0\1\122\36\0"+
    "\1\61\31\0\2\63\57\0\5\6\15\0\2\6\1\123"+
    "\5\6\10\0\14\6\6\0\5\6\15\0\10\6\10\0"+
    "\1\124\13\6\6\0\5\6\15\0\1\125\7\6\10\0"+
    "\14\6\6\0\5\6\15\0\7\6\1\126\10\0\14\6"+
    "\6\0\5\6\15\0\1\127\7\6\10\0\14\6\6\0"+
    "\5\6\15\0\6\6\1\130\1\6\10\0\14\6\6\0"+
    "\5\6\15\0\10\6\10\0\2\6\1\131\11\6\6\0"+
    "\5\6\15\0\1\6\1\132\3\6\1\133\2\6\10\0"+
    "\14\6\6\0\5\6\15\0\1\134\7\6\10\0\14\6"+
    "\6\0\5\6\15\0\5\6\1\135\2\6\10\0\14\6"+
    "\6\0\5\6\15\0\10\6\10\0\2\6\1\136\11\6"+
    "\6\0\5\6\15\0\6\6\1\137\1\6\10\0\14\6"+
    "\6\0\5\6\15\0\10\6\10\0\11\6\1\140\2\6"+
    "\6\0\5\6\15\0\3\6\1\141\4\6\10\0\14\6"+
    "\6\0\5\6\15\0\10\6\10\0\4\6\1\142\7\6"+
    "\6\0\5\6\15\0\10\6\10\0\1\143\13\6\6\0"+
    "\5\6\15\0\10\6\10\0\1\144\13\6\6\0\5\6"+
    "\15\0\3\6\1\145\4\6\10\0\14\6\6\0\5\6"+
    "\15\0\7\6\1\146\10\0\14\6\6\0\5\6\15\0"+
    "\2\6\1\147\5\6\10\0\14\6\6\0\5\6\15\0"+
    "\3\6\1\150\4\6\10\0\14\6\6\0\5\6\15\0"+
    "\3\6\1\151\4\6\10\0\14\6\6\0\5\6\15\0"+
    "\7\6\1\152\10\0\14\6\6\0\5\6\15\0\10\6"+
    "\10\0\7\6\1\153\4\6\6\0\5\6\15\0\10\6"+
    "\10\0\1\154\13\6\6\0\5\6\15\0\1\155\7\6"+
    "\10\0\14\6\6\0\5\6\15\0\7\6\1\156\10\0"+
    "\14\6\6\0\5\6\15\0\1\157\7\6\10\0\14\6"+
    "\6\0\5\6\15\0\6\6\1\160\1\6\10\0\14\6"+
    "\6\0\5\6\15\0\5\6\1\161\2\6\10\0\14\6"+
    "\6\0\5\6\15\0\6\6\1\162\1\6\10\0\14\6"+
    "\6\0\5\6\15\0\10\6\10\0\6\6\1\163\5\6"+
    "\6\0\5\6\15\0\6\6\1\164\1\6\10\0\14\6"+
    "\6\0\5\6\15\0\1\6\1\165\6\6\10\0\14\6"+
    "\6\0\5\6\15\0\10\6\10\0\2\6\1\166\11\6"+
    "\6\0\5\6\15\0\3\6\1\167\4\6\10\0\14\6"+
    "\6\0\5\6\15\0\1\170\7\6\10\0\14\6\6\0"+
    "\5\6\15\0\10\6\10\0\2\6\1\171\11\6\6\0"+
    "\5\6\15\0\10\6\10\0\1\172\13\6\6\0\5\6"+
    "\15\0\7\6\1\173\10\0\14\6\6\0\5\6\15\0"+
    "\10\6\10\0\1\174\13\6\6\0\5\6\15\0\10\6"+
    "\10\0\12\6\1\175\1\6\6\0\5\6\15\0\3\6"+
    "\1\176\4\6\10\0\14\6\6\0\5\6\15\0\3\6"+
    "\1\177\4\6\10\0\14\6\6\0\5\6\15\0\10\6"+
    "\10\0\2\6\1\200\11\6\6\0\5\6\15\0\10\6"+
    "\10\0\6\6\1\201\5\6\6\0\5\6\15\0\10\6"+
    "\10\0\10\6\1\202\3\6\6\0\5\6\15\0\10\6"+
    "\10\0\7\6\1\203\4\6\6\0\5\6\15\0\10\6"+
    "\10\0\1\6\1\204\12\6\6\0\5\6\15\0\10\6"+
    "\10\0\2\6\1\205\11\6\6\0\5\6\15\0\5\6"+
    "\1\206\2\6\10\0\14\6\6\0\5\6\15\0\7\6"+
    "\1\207\10\0\14\6\6\0\5\6\15\0\2\6\1\210"+
    "\5\6\10\0\14\6\6\0\5\6\15\0\10\6\10\0"+
    "\2\6\1\211\11\6\6\0\5\6\15\0\3\6\1\212"+
    "\4\6\10\0\14\6\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4524];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\11\4\1\7\11\14\1\3\11\1\1\4\11"+
    "\6\1\2\11\1\1\2\11\1\1\1\11\2\1\6\11"+
    "\10\1\2\11\12\1\5\11\70\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[138];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
      StringBuffer string = new StringBuffer(); /* to save strings' values. */
     
     /* to save comment and str. init. line, for lexical errors. */
      private int comm_init_line=0; 
      private int str_init_line=0;
      
      /* help functions for tokens return. */
      
      private Token token(int id) {
		  return new Token(id, yyline+1);  /* as counting starts from 0 and we want from 1. */
	  }
		
		
	  private Token token(int id, Object value) {
		  return new Token(id, yyline+1, value);
	  }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) throws LexicalError {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new LexicalError(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  throws LexicalError {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token next_token() throws java.io.IOException, LexicalError {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 2: 
          { return token(sym.ID,yytext());
          }
        case 63: break;
        case 8: 
          { return token(sym.LB,yytext());
          }
        case 64: break;
        case 61: 
          { return token(sym.BOOLEAN,yytext());
          }
        case 65: break;
        case 39: 
          { return token(sym.IF,yytext());
          }
        case 66: break;
        case 12: 
          { return token(sym.ASSIGN,yytext());
          }
        case 67: break;
        case 27: 
          { yybegin(YYINITIAL); 
						  string.append('\"'); 
		       			  return token(sym.QUOTE,string.toString());
          }
        case 68: break;
        case 56: 
          { return token(sym.RETURN,yytext());
          }
        case 69: break;
        case 35: 
          { return token(sym.LOR,yytext());
          }
        case 70: break;
        case 52: 
          { return token(sym.FALSE,yytext());
          }
        case 71: break;
        case 22: 
          { return token(sym.SEMI,yytext());
          }
        case 72: break;
        case 32: 
          { return token(sym.NEQUAL,yytext());
          }
        case 73: break;
        case 17: 
          { return token(sym.MINUS,yytext());
          }
        case 74: break;
        case 1: 
          { throw new LexicalError("Lexical error: illegal character '" + yytext() + "'",yyline+1);
          }
        case 75: break;
        case 15: 
          { return token(sym.GT,yytext());
          }
        case 76: break;
        case 11: 
          { return token(sym.RCBR,yytext());
          }
        case 77: break;
        case 21: 
          { return token(sym.COMMA,yytext());
          }
        case 78: break;
        case 9: 
          { return token(sym.RB,yytext());
          }
        case 79: break;
        case 54: 
          { return token(sym.BREAK,yytext());
          }
        case 80: break;
        case 5: 
          { /* ignore. */
          }
        case 81: break;
        case 38: 
          { yybegin(INLINE_COMMENT);
          }
        case 82: break;
        case 46: 
          { return token(sym.NEW,yytext());
          }
        case 83: break;
        case 41: 
          { string.append("\\t");
          }
        case 84: break;
        case 60: 
          { return token(sym.EXTENDS,yytext());
          }
        case 85: break;
        case 45: 
          { return token(sym.INT,yytext());
          }
        case 86: break;
        case 20: 
          { return token(sym.MOD,yytext());
          }
        case 87: break;
        case 29: 
          { yybegin(YYINITIAL);
          }
        case 88: break;
        case 37: 
          { comm_init_line=yyline; yybegin(REGULAR_COMMENT);
          }
        case 89: break;
        case 24: 
          { str_init_line=yyline; string.setLength(0); string.append('\"'); yybegin(STRING);
          }
        case 90: break;
        case 23: 
          { return token(sym.DOT,yytext());
          }
        case 91: break;
        case 16: 
          { return token(sym.PLUS,yytext());
          }
        case 92: break;
        case 40: 
          { throw new LexicalError("Lexical error: illegal escape sequence inside of a string: '" + yytext() + "'",yyline+1);
          }
        case 93: break;
        case 28: 
          { throw new LexicalError("Lexical error: Unclosed string at end of line.",str_init_line+1);
          }
        case 94: break;
        case 53: 
          { return token(sym.CLASS,yytext());
          }
        case 95: break;
        case 48: 
          { return token(sym.THIS,yytext());
          }
        case 96: break;
        case 10: 
          { return token(sym.LCBR,yytext());
          }
        case 97: break;
        case 44: 
          { string.append("\\\\");
          }
        case 98: break;
        case 6: 
          { return token(sym.LP,yytext());
          }
        case 99: break;
        case 4: 
          { return token(sym.INTEGER, yytext());
          }
        case 100: break;
        case 18: 
          { return token(sym.MULTIPLY,yytext());
          }
        case 101: break;
        case 33: 
          { return token(sym.LTE,yytext());
          }
        case 102: break;
        case 50: 
          { return token(sym.NULL,yytext());
          }
        case 103: break;
        case 55: 
          { return token(sym.WHILE,yytext());
          }
        case 104: break;
        case 47: 
          { return token(sym.TRUE,yytext());
          }
        case 105: break;
        case 30: 
          { throw new LexicalError("Lexical error: integer should not have leading zeros.",yyline+1);
          }
        case 106: break;
        case 57: 
          { return token(sym.LENGTH,yytext());
          }
        case 107: break;
        case 26: 
          { string.append(yytext());
          }
        case 108: break;
        case 31: 
          { return token(sym.EQUAL,yytext());
          }
        case 109: break;
        case 14: 
          { return token(sym.LT,yytext());
          }
        case 110: break;
        case 49: 
          { return token(sym.ELSE,yytext());
          }
        case 111: break;
        case 43: 
          { string.append("\\\"");
          }
        case 112: break;
        case 13: 
          { return token(sym.LNEG,yytext());
          }
        case 113: break;
        case 19: 
          { return token(sym.DIVIDE,yytext());
          }
        case 114: break;
        case 59: 
          { return token(sym.STATIC,yytext());
          }
        case 115: break;
        case 7: 
          { return token(sym.RP,yytext());
          }
        case 116: break;
        case 51: 
          { return token(sym.VOID,yytext());
          }
        case 117: break;
        case 58: 
          { return token(sym.STRING,yytext());
          }
        case 118: break;
        case 62: 
          { return token(sym.CONTINUE,yytext());
          }
        case 119: break;
        case 42: 
          { string.append("\\n");
          }
        case 120: break;
        case 25: 
          { throw new LexicalError("Lexical error: illegal character inside of a string: '" + yytext() + "'",yyline+1);
          }
        case 121: break;
        case 3: 
          { return token(sym.CLASS_ID,yytext());
          }
        case 122: break;
        case 36: 
          { return token(sym.LAND,yytext());
          }
        case 123: break;
        case 34: 
          { return token(sym.GTE,yytext());
          }
        case 124: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              { 
	if (yystate() == STRING)   /* EOF inside string. */
		throw new LexicalError("Lexical error: Unclosed string at end of file.",str_init_line+1);
		
 	if (yystate() == REGULAR_COMMENT)  /* EOF inside comment. */
 		throw new LexicalError("Lexical error: Unclosed comment at end of file.",comm_init_line+1);
 		 
  	return token(sym.EOF,"EOF");
  	
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
