
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jan 17 17:45:27 IST 2013
//----------------------------------------------------

package IC.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 11;
  public static final int LCBR = 6;
  public static final int LTE = 18;
  public static final int UMINUS = 13;
  public static final int INTEGER = 48;
  public static final int CONTINUE = 38;
  public static final int SEMI = 27;
  public static final int INT = 30;
  public static final int MINUS = 9;
  public static final int STATIC = 29;
  public static final int LT = 17;
  public static final int LP = 2;
  public static final int COMMA = 26;
  public static final int CLASS = 44;
  public static final int RP = 3;
  public static final int PLUS = 8;
  public static final int MULTIPLY = 10;
  public static final int QUOTE = 49;
  public static final int IF = 40;
  public static final int ASSIGN = 14;
  public static final int THIS = 35;
  public static final int ID = 46;
  public static final int DOT = 28;
  public static final int EOF = 0;
  public static final int BOOLEAN = 31;
  public static final int RETURN = 39;
  public static final int RCBR = 7;
  public static final int LB = 4;
  public static final int LAND = 23;
  public static final int EQUAL = 15;
  public static final int TRUE = 24;
  public static final int NEW = 42;
  public static final int error = 1;
  public static final int RB = 5;
  public static final int LOR = 22;
  public static final int NULL = 34;
  public static final int MOD = 12;
  public static final int BREAK = 37;
  public static final int VOID = 32;
  public static final int GTE = 20;
  public static final int ELSE = 41;
  public static final int WHILE = 36;
  public static final int NEQUAL = 16;
  public static final int CLASS_ID = 47;
  public static final int EXTENDS = 45;
  public static final int STRING = 33;
  public static final int LNEG = 21;
  public static final int FALSE = 25;
  public static final int GT = 19;
  public static final int LENGTH = 43;
}

